#.travis.yml

sudo: required

dist: trusty

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
    sonarcloud:
      organization: "ismaestro-github"
      token:
        secure: $SONAR_TOKEN 

language: node_js

node_js:
  - 10.16.0

branches:
  only:
    - master

before_script:
  - set -e
  - npm install
  - npm run build:library
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm run lint
  - npm run test
  - npm run e2e
  - npm run build:ssr

after_script:
  - set +e
  - sonar-scanner
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

notifications:
  email:
    on_failure: change
    on_success: change
