#.travis.yml

dist: trusty

sudo: required

language: node_js

node_js:
  - 10.16.0

branches:
  only:
    - master

git:
  depth: false

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
  sonarcloud:
    organization: "ismaestro-github"
    token:
      secure: $SONAR_TOKEN

before_script:
  - set -e
  - npm install
  - npm run build:library
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

script:
  - npm run lint
  - npm run test
  - npm run e2e
  - npm run build:ssr
  - npm run validate:server
  - sonar-scanner

before_deploy:
  - npm run prepare:deploy

deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
  project: "ismaestro-angularexampleapp"

notifications:
  email:
    on_failure: change
    on_success: change
