#.travis.yml

language: node_js
node_js:
  - "6.9"

branches:
  only:
    - master

before_script:
  - npm install
  - npm start
  - npm run e2e

script:
  - ng build --prod

notifications:
  email:
    on_failure: change
    on_success: change