#.travis.yml

sudo: required

dist: trusty

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

language: node_js

node_js:
  - 6
  - 7

branches:
  only:
    - master

before_script:
  - npm install
  - npm install -g angular-cli-ghpages
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm run lint
  - npm run e2e
  - ng build --prod --base-href /angular4-example-app/
  - angular-cli-ghpages --repo=https://GH_TOKEN@$GH_REPO --name="New release" --email=ramossilvanismael@gmail.com

notifications:
  email:
    on_failure: change
    on_success: change