#.travis.yml

language: node_js
node_js:
  - "6.9"

branches:
  only:
    - master

before_script:
  - npm install

script:
  - ng build --prod
  - angular-cli-ghpages

notifications:
  email:
    on_failure: change
    on_success: change