#.travis.yml

sudo: required

dist: trusty

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
  sonarcloud:
    organization: "ismaestro-github"
    token:
      secure: $SONAR_TOKEN

language: node_js

node_js:
  - 10.16.0

branches:
  only:
    - master

before_script:
  - set -e
  - npm install
  - npm run build:library
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm run lint
  - npm run test
  - npm run e2e
  - npm run build:ssr

after_script:
  - sonar-scanner
  - set +e
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

before_deploy:
  - mkdir public
  - cp -a dist/browser/. public/
  - mv public/assets/common/* public/
  - rm -Rf public/assets/common public/es/assets/common
  - mv public/index.html public/index2.html
  - mv public/es/index.html public/es/index2.html
  - cp -a dist/ functions/dist

deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
  project: "ismaestro-angularexampleapp"

notifications:
  email:
    on_failure: change
    on_success: change
